### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by 22620188Oliverio** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-22620188Oliverio#1]
[Infografia_Oliverio Rojas Sanchez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-22620188Oliverio/files/14530224/Infografia_Oliverio.Rojas.Sanchez.pdf)

**Comment by Bryan080204** [comment]
18
falto estructurar  su informacion

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
